//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.9.0 (NJsonSchema v10.6.8.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace VMware.VCDRService
{
    using System;
    using System.Threading;
    using System.Net.Http;
    /// <summary>
    /// Detailed information about an individual cloud file system.
    /// </summary>
    public class CloudFileSystem : CloudFileSystemDetails
    {

        public string IRRServer { get; set; }
        public CloudFileSystem(CloudFileSystemDetails c)
        {
            // copy base class properties.
            foreach (var prop in c.GetType().GetProperties())
            {
                var prop2 = c.GetType().GetProperty(prop.Name);
                prop2.SetValue(this, prop.GetValue(c, null), null);
            }

        }
    }


    /// <summary>
    /// Detailed information for protection groups.
    /// </summary>
    public class ProtectionGroup : ProtectionGroupDetails
    {
        /// <summary>
        /// Cloud file system unique identifier.
        /// </summary> 
        public string CloudFileSystemId { get; set; }
        public ProtectionGroup(ProtectionGroupDetails c)
        {
            // copy base class properties.
            foreach (var prop in c.GetType().GetProperties())
            {
                var prop2 = c.GetType().GetProperty(prop.Name);
                prop2.SetValue(this, prop.GetValue(c, null), null);
            }

        }
    }


    /// <summary>
    /// Detailed information about protected sites.
    /// </summary>
    public class ProtectedSite : ProtectedSiteDetails
    {
        /// <summary>
        /// Cloud file system unique identifier.
        /// </summary> 
        public string CloudFileSystemId { get; set; }
        public ProtectedSite(ProtectedSiteDetails c)
        {
            // copy base class properties.
            foreach (var prop in c.GetType().GetProperties())
            {
                var prop2 = c.GetType().GetProperty(prop.Name);
                prop2.SetValue(this, prop.GetValue(c, null), null);
            }

        }
    }



    public class ProtectionGroupSnapshot : ProtectionGroupSnapshotDetails
    {
        /// <summary>
        /// Cloud file system unique identifier.
        /// </summary> 
        public string CloudFileSystemId { get; set; }
        public ProtectionGroupSnapshot(ProtectionGroupSnapshotDetails c)
        {
            // copy base class properties.
            foreach (var prop in c.GetType().GetProperties())
            {
                var prop2 = c.GetType().GetProperty(prop.Name);
                prop2.SetValue(this, prop.GetValue(c, null), null);
            }

        }
    }

    /// <summary>
    /// Detailed information about Recovery SDDCs.
    /// </summary>
    public class RecoverySddc : RecoverySddcDetails
    {  
        public RecoverySddc(RecoverySddcDetails c)
        {
            // copy base class properties.
            foreach (var prop in c.GetType().GetProperties())
            {
                var prop2 = c.GetType().GetProperty(prop.Name);
                prop2.SetValue(this, prop.GetValue(c, null), null);
            }

        }
    }


}
#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore 472
#pragma warning restore 114
#pragma warning restore 108
#pragma warning restore 3016
#pragma warning restore 8603